### ISSUE TITLE
Sort feature requested

### ISSUE THREAD

**Issue by ykaragol** [tubitak-bilgem-yte/ember-contextual-table#1]
Table needs sort feature. An alternative could be seen in [here](https://github.com/ykaragol/table-test/compare/feature-sortable).

**Comment by chilicoder** [comment]
@ykaragol I think your approach violating open/close principle
Better approach IMHO is to implement wrapping component like with `data-paginator` to have in the end something like this:

```
{{#data-sorter data=data sortingKey='Name' sorting='asc' as |s|}}
  {{#data-paginator data=s.data pageSize=3 as |p|}}
      {{#data-table data=p.data as |t|}}
     ...
      {{/data-table}}
      {{pager-component next=p.next previous=p.previous currentPage=p.currentPage
          nextDisabled=(if p.hasNext false true)}}
  {{/data-paginator}}
{{/data-sorter}}
```

**Comment by feanor07** [comment]
@chilicoder that is brilliant; we have been thinking about it for some time. you are welcome to contribute with this approach. we will try to implement it if we have time soon.

**Comment by chilicoder** [comment]
I will make a try)

**Comment by feanor07** [comment]
@chilicoder i will release the sorting within a few days. I think we will also include filtering as a core feature to the table; so that for basic filtering users will not have to writer boilerplate code.

**Comment by ykaragol** [comment]
Closed with https://github.com/tubitak-bilgem-yte/ember-contextual-table/pull/6
