### ISSUE TITLE
Is possible to add sorting and filtering to a remote date table?

### ISSUE THREAD

**Issue by hugoruscitti** [tubitak-bilgem-yte/ember-contextual-table#15]
I'm starting a simple demo using ember-contextural-table that fech remote data using something similar to the "Remote Calling Paginated Table" example showed in the demo site: https://tubitak-bilgem-yte.github.io/ember-contextual-table/#/pagination

But i don't see a way to extends that example to support some advanced filtering or search field.

any advice?

**Comment by feanor07** [comment]
sorry for the late reply. we have quite been busy for sometime. did you solve your issue or is it still a problem? is there any source code that you have tried and not worked; which you can share with use through ember twiddle or github?

I assume the examples on the guide should also work for remote calling paginated tables; there should not be any problems.

**Comment by feanor07** [comment]
closing this issue since it has been quite some time without any activity and we do not know what to do with this issue.
