### ISSUE TITLE
Bug of data-filterer

### ISSUE THREAD

**Issue by kaermorchen** [tubitak-bilgem-yte/ember-contextual-table#17]
When I use data-filterer and change length of data from external action, it doesn't make changes in the table.

```
{{#data-filterer data=model as |df|}}
    {{#data-table data=df.data classNames=tableClassNames as |t|}}
        ...
    {{/data-table}}
  {{/data-filterer}}
```

```
actions: {
    removeUser(user) {
        this.get('model').removeObject(user);
    }
}
```

But if you add key 'data.[]' into 
https://github.com/tubitak-bilgem-yte/ember-contextual-table/blob/d5ff6e1e5c4808e491294087ee189a3bcdd1db15/addon/components/data-filterer.js#L43
it will work fine.

**Comment by ykaragol** [comment]
Thank you! I've created a pr for this.

**Comment by ykaragol** [comment]
version 1.8.1 published to npm.
