### ISSUE TITLE
Set id on row

### ISSUE THREAD

**Issue by sfbwalder** [tubitak-bilgem-yte/ember-contextual-table#19]
We would like to set an id on each row for testing.  Is there a way to do this?

Would like the end result to be something like this... where the value of the id is somehow passed as a parameter.
```hbs
<!-- data-table.hbs -->
{{#each data as |row index|}}
    <tr id="id-for-testing"
      class={{if (array-contains selectedRows row) 'contextual-table-selected-row contextual-table-row' 'contextual-table-row'}} {{action (if (array-contains selectedRows row) 'deselected' 'selected') row on='doubleClick'}}>
```

Your help on this is appreciated.

**Comment by ykaragol** [comment]
For now, I couldn't see a way to achieve this. May be we can generate an id for `tr`s. 

While testing we are accessing the rows or cells via jquery, such as: 

    Ember.$('.contextual-data-table:eq(0)` .contextual-table-row:eq(2)')

This gaves the first table's 3th row in the page (and skips the extra-rows). 

Maybe we can consider to provide some test-helpers with addon.

**Comment by feanor07** [comment]
With version 1.9.0; you can now pass `rowIdPrefix` property to `data-table` and your rows will have the following ids assigned to them if you pass `customRowIdPrefix` as value:

first row: `customRowIdPrefix-0`
second row: `customRowIdPrefix-1` and so on.

if you omit to pass `rowIdPrefix` yourself; default value for `rowIdPrefix` property is `table-row-id`.

I guess this will ease the way to test your rows. I am closing the issue for now; if you think there is more to be done you can just submit a pull request or re-open and comment or even create a new issue. Best regards.
