### ISSUE TITLE
Open up single click on rows?

### ISSUE THREAD

**Issue by lumenlunae** [tubitak-bilgem-yte/ember-contextual-table#30]
Double-click is available, but would you be willing to open up a single click action we can use? I'd be willing to make a PR potentially this week.

**Comment by feanor07** [comment]
you are welcome for the PR.

**Comment by ahmetemrekilinc** [comment]
onRowDoubleClick and onRowSingleClick action params are added in version 3.1.3 
Example usages can be found in row click handling page of demo app https://tubitak-bilgem-yte.github.io/ember-contextual-table/
