### ISSUE TITLE
Plan for Ember 3.0 migration

### ISSUE THREAD

**Issue by ykaragol** [tubitak-bilgem-yte/ember-contextual-table#31]
"Ember 3.0 beta" has released. "Ember 3.0" will be released in a couple of weeks.  There need a plan for migration.

**Comment by ykaragol** [comment]
For 2.16 migration, [ember-modules-codemod](https://github.com/ember-cli/ember-modules-codemod) may help.

**Comment by ctcpip** [comment]
@ykaragol is this project abandoned?

**Comment by ctcpip** [comment]
@ykaragol ?  @feanor07 ?

**Comment by ykaragol** [comment]
@ctcpip 
Thanks for asking. No, it is not abandoned. I've switched my company so I couldn't find anytime to upgrade this project. 

//cc @ahmetemrekilinc

**Comment by ahmetemrekilinc** [comment]
@ctcpip I can update to ember 3.5.0 in a few days.

**Comment by ctcpip** [comment]
@ahmetemrekilinc Great!

**Comment by ahmetemrekilinc** [comment]
@ctcpip  I am currently waiting for authorization for this repo from my company. I don't know when can I get it, sorry.

**Comment by ahmetemrekilinc** [comment]
ember-cli is upgraded to 3.5.1.
https://github.com/tubitak-bilgem-yte/ember-contextual-table/pull/38
