### ISSUE TITLE
Cannot pass down an action to click event handler due to empty-component having no tag name

### ISSUE THREAD

**Issue by vmalchik** [tubitak-bilgem-yte/ember-contextual-table#33]
An error occurs when assigning an action to a click event. 

Error: 
You can not define a function that handles DOM events in the `<ui@component:empty-component::ember1095>` tagless component since it doesn't have any DOM element.

How to reproduce error: 
{{#data-table data=ds.data as |t|}}
  {{t.column
    propertyName='somePropertyName'
    name='Some Name'
    click=(action 'myAction' t.row)}}
{{/data-table}}

Cause:
https://github.com/tubitak-bilgem-yte/ember-contextual-table/blob/master/addon/components/empty-component.js used https://github.com/tubitak-bilgem-yte/ember-contextual-table/blob/master/addon/templates/data-table.hbs#L33

Empty component has no tagName which causes the error. I am also curious about the need for having an empty-component? 
https://github.com/tubitak-bilgem-yte/ember-contextual-table/blob/master/addon/templates/data-table.hbs#L33-L36
and
https://github.com/tubitak-bilgem-yte/ember-contextual-table/blob/master/addon/templates/data-table.hbs#L12

**Comment by ykaragol** [comment]
Thanks for reporting, a PR will be published today.

**Comment by feanor07** [comment]
we have fixed that with 2.0.1 release.
