### ISSUE TITLE
sort column on header click 

### ISSUE THREAD

**Issue by ctcpip** [tubitak-bilgem-yte/ember-contextual-table#41]
right now, the sort event only fires if you click on the text.  instead, clicking anywhere on the header should fire the sort event.

**Comment by ahmetemrekilinc** [comment]
Fixed in version 3.1.2
https://github.com/tubitak-bilgem-yte/ember-contextual-table/commit/98f2b9d722a0b8fe1ad5005a0ae832065ab20703
