### ISSUE TITLE
Remove empty spans between <tr>'s

### ISSUE THREAD

**Issue by cecemel** [tubitak-bilgem-yte/ember-contextual-table#47]
It seems the addon renders spans between subsequent <tr> elements:
```
<tr id="ember823-table-row-id-1" class="contextual-table-row">  <!-- row info --> </tr>
<span id="ember2223" style="display: none;" class="ember-view"></span>
<tr id="ember823-table-row-id-2" class="contextual-table-row">  <!-- row info --> </tr>
```
According to MDN, this doesn't seem to be legal html:
[https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tbody](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tbody)

The extra spans are also visible in e.g. [https://tubitak-bilgem-yte.github.io/ember-contextual-table/basic-usage](https://tubitak-bilgem-yte.github.io/ember-contextual-table/basic-usage)

**Comment by esrgrlk** [comment]
Fixed in version 3.6.1
