### ISSUE TITLE
Don't render hidden rows when using {{#t.extraRow as |er|}}

### ISSUE THREAD

**Issue by cecemel** [tubitak-bilgem-yte/ember-contextual-table#48]
When using the detail row mode, when the detail view is not used, hidden and empty rows are added to the DOM. I guess as place holders. 

```
      {{#t.extraRow as |er|}}
        {{#if (ember-array-includes detailRowsToDisplay er.rowIndex)}}
          <td class="deployment-row--sub" colspan="6">
            {{tables/browse-deployments-detail-row deployment=er.row class="deployment-row--content"}}
          </td>
        {{/if}}
      {{/t.extraRow}}
```
This brings a couple of styling issues, like e.g a striped table, which won't work any more. I don't know whether there would be a work around like: 

```
   {{!-- if detail view is selected }}

      {{#t.extraRow as |er|}}
        {{#if (ember-array-includes detailRowsToDisplay er.rowIndex)}}
          <td class="deployment-row--sub" colspan="6">
            {{tables/browse-deployments-detail-row deployment=er.row class="deployment-row--content"}}
          </td>
        {{/if}}
      {{/t.extraRow}}

  {{!-- /if --}
```

**Comment by esrgrlk** [comment]
extraRow adds _tr_ tag by default, so if control should be placed outside of extraRow code block.
You can change your code accordingly:   

  {{#if (ember-array-includes detailRowsToDisplay t.rowIndex)}}
        {{#t.extraRow as |er|}}
          <td class="deployment-row--sub" colspan="6">
            {{tables/browse-deployments-detail-row deployment=er.row class="deployment-row--content"}}
          </td>
      {{/t.extraRow}}
  {{/if}}

Our demo code was also wrong and we changed demo example code, too. 
You can also see example usage in 'Row Detail Displaying' page:
https://tubitak-bilgem-yte.github.io/ember-contextual-table
